spring:
    application:
        name: Aplusmarket
    jackson:
        time-zone: Asia/Seoul
    devtools:
        livereload:
            enabled: true
    datasource:
        url: jdbc:mysql://43.202.32.28:3306/applusmarket?serverTimezone=Asia/Seoul
        username: applus
        password: Qwe1234~!
        driver-class-name: com.mysql.cj.jdbc.Driver
        mybatis:
            mapper-locations: classpath:mapper/**/*.xml  # 매퍼 XML 파일 경로
            config-location: classpath:mybatis-config.xml  # MyBatis 설정 파일 경로 (선택)
            type-aliases-package: com.aplus.aplusmarket # TypeAlias 사용할 패키지 경로

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
                use_sql_comments: true
        show-sql: true
    servlet:
        multipart:
            enabled: true
            location: uploads/
    data:
        mongodb:
            uri: mongodb://root:Qwe1234~!@43.202.32.28:27017/applus?authSource=admin

mybatis:
    mapper-locations: classpath:mapper/**/*.xml  # 매퍼 XML 파일 경로
    config-location: classpath:mybatis-config.xml  # MyBatis 설정 파일 경로 (선택)
    type-aliases-package: com.aplus.aplusmarket.entity # TypeAlias 사용할 패키지 경로
server:
    port: 8080
    servlet:
        context-path: /
    address: 0.0.0.0

logging:
    level:
        org.mybatis: DEBUG
        org.springframework: INFO
token:
    jwt:
        secret: "UexkyuXOpB7ApyOmIXm0zn23EE/ZLlbdRHFIronNyvHb1NoipAZHj2App1HBm8RwCSmHUzzWYRRL61OyAST2TQ=="
        issuer: "applusmarket"

#2024.02.04 이도영 이미지 파일 경로 추가
file:
    upload:
        path: uploads
